variables:
    PACKAGE_PATH: /go/src/app
    GIT_SUBMODULE_STRATEGY: recursive
    GOPROXY: direct
stages:
    - build
    - deploy

build:
    stage: build
    image: docker:latest
    tags: [dockerexec]
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - docker build -f Dockerfile --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHORT_SHA .
        - docker push $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHORT_SHA
