variables:
    PACKAGE_PATH: /go/src/app

stages:
    - build
    - deploy

build:
    stage: build
    image: docker:latest
    tags: [dockerexec]
    script:
        - docker build -f Dockerfile -t simple-rest .
