variables:
    PACKAGE_PATH: /go/src/app

stages:
    - build
    - deploy

build:
    stage: build
    image: docker:17
    services:
      - docker:dind
    script:
        - export DOCKER_HOST="tcp://localhost:2375"
        - docker build -t simple-rest .
